### ISSUE TITLE
missing type DocumentAndElementEventHandlers from elements.d.ts

### ISSUE THREAD

**Issue by marcusho21** [ryansolid/component-register#24]
I tried to use solid-element to setup a web component library project, but for some reason when trying to generate types during build, it throws error 

```bash
../../node_modules/component-register/types/element.d.ts:185:26 - error TS2304: Cannot find name 'DocumentAndElementEventHandlers'.
```

**Comment by randjey** [comment]
bump! I'm having the same issue here. Tried many different stuff and can't seem to have any tsconfig that solves it.

**Comment by Etienne-M** [comment]
On the consumer side, the only thing we can do is adding
```
    "skipLibCheck": true
```
to our tsconfig, which basically does not check any typing in libraries, which is a shame.

This should be fixed in this project. To fix this issue here, there needs to be support for TS5. In short, there's two things that can be done, either
- Update the typescript version; or,
- Build the typings twice, once with TS4 and once with TS5, and [expose both in the package json](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions).
